### ISSUE TITLE
std::iter::Extend for bimap

### ISSUE THREAD

**Issue by nw0** [billyrieger/bimap-rs#11]
Hi, I've found your crate useful and have experimented with implementing `std::iter::Extend` for `BiHashMap`.

I have a working implementation (with test), and was wondering if you'd have any interest in a PR? If so I'll open one and we can iterate from there if necessary.

It's straightforward (15 lines) and I'm happy to implement the trait for `BiBTreeMap` as well, if that's helpful.

**Comment by billyrieger** [comment]
That would be great! I think it'd be best to implement `Extend` for both `BiHashMap` and `BiBTreeMap`.
