### ISSUE TITLE
impl DoubleEndedIterator for IntoIter

### ISSUE THREAD

**Issue by Skarlett** [billyrieger/bimap-rs#35]
I noticed that `DoubleEndedIterator` could be implemented for the internal `IntoIter` structure. This would add on methods such as `rev()` `next_back()`

I'll likely make a fork with the appropriate modifications, and open up a pull request if all looks good to you.

Also, could you note somewhere in the documentation if ordering is preserved during iteration, thanks.

**Comment by billyrieger** [comment]
Yes, I'd be happy to review a pull request with those changes. The iteration order is preserved for BiBTreeMap but not for BiHashMap. I can make a note of that in the module documentation.

**Comment by flokli** [comment]
@Skarlett did you get around to open that PR? I'm currently trying to use the `*_range` methods to find the next neighbor, which also only works into the increasing direction.

**Comment by Skarlett** [comment]
> @Skarlett did you get around to open that PR? I'm currently trying to use the `*_range` methods to find the next neighbor, which also only works into the increasing direction.

Ah, sorry. I've been busy under a new umbrella and haven't gotten to writing it.

**Comment by GrigorenkoPV** [comment]
Isn't it already implemented?
https://github.com/billyrieger/bimap-rs/blob/3dca651620845a939ee9e5393c0a8fe9fe0a1656/src/btree.rs#L735

**Comment by flokli** [comment]
Yes, you were right. Sorry for the noise. Looks like this issue can be closed.
