### ISSUE TITLE
Serde compatibility

### ISSUE THREAD

**Issue by dmarcuse** [billyrieger/bimap-rs#6]
I just stumbled across this crate, it seems pretty useful! However, it would be nice to be able to serialize and deserialize the maps out of the box with serde. I'm happy to implement the functionality and open a PR if you think it would be a good feature to include. It would probably be a good idea to gate this functionality behind a feature (`serde`) so that the crate can be used without unnecessarily pulling in extra dependencies when this isn't needed.

**Comment by billyrieger** [comment]
Hi! That sounds like a good feature to have, I'd be happy to accept a PR for `serde` compatibility. Putting it behind a feature flag is definitely the best option.

**Comment by dmarcuse** [comment]
Alright, I'll get started on it. A few quick questions about implementation details:

- I'll be gating serde integration behind a feature, but should the feature be enabled by default? I think it shouldn't be, to minimize dependencies for people who don't need it and don't manually select features.
- How should it interact with the `std` feature? serde supports no_std environments, but I feel like this would complicate things significantly, so I think it would be best to initially have the `serde` feature require the `std` feature to make it easier to implement.

**Comment by billyrieger** [comment]
I'm on board with both of those decisions (not enabled by default, dependent on the `std` feature).

**Comment by dmarcuse** [comment]
Great, I'll get started.

**Comment by billyrieger** [comment]
Fixed by #7.

**Comment by dmarcuse** [comment]
Would it be possible to publish 0.2.1 (or a different version if you prefer) so I can start using this?

**Comment by billyrieger** [comment]
Sure thing. I'm going to add some other small changes I've been meaning to make and `0.3` should be out sometime tonight.

**Comment by dmarcuse** [comment]
Sounds good!

**Comment by billyrieger** [comment]
Just published `0.3.0`.

**Comment by dmarcuse** [comment]
Great, thanks again!
